{
 "title": "Heating Template",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Gas Energy Consumed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": " delta(value{instance=\"192.168.1.12:9001\", job=\"gasmeter_exporter\"}[1h]) * brennwert{instance=\"192.168.1.12:9001\", job=\"gasmeter_exporter\"}\r\n* zustandszahl{instance=\"192.168.1.12:9001\", job=\"gasmeter_exporter\"}",
     "legendFormat": "Gas usage per hour"
    }
   ]
  },
  {
   "title": "Gas Consumed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m³" } },
   "targets": [
    {
     "expr": "value{instance=\"192.168.1.12:9001\", job=\"gasmeter_exporter\"}",
     "legendFormat": "Gas usage total"
    }
   ]
  },
  {
   "title": "Gas Price",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "gaspreis{instance=\"192.168.1.12:9001\", job=\"gasmeter_exporter\"}",
     "legendFormat": "Price for kWh Gas "
    }
   ]
  },
  {
   "title": "Gas Consumed Last Hour",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(value{instance=\"192.168.1.12:9001\", job=\"gasmeter_exporter\"}[1h])  *0.9587 * 11.404",
     "legendFormat": " "
    },
    {
     "expr": "delta(value_in_eur{instance=\"192.168.1.12:9001\", job=\"gasmeter_exporter\"}[1h]) ",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Gas Consumed Last 24h",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(value{instance=\"192.168.1.12:9001\", job=\"gasmeter_exporter\"}[24h])  *0.9587 * 11.404",
     "legendFormat": " "
    },
    {
     "expr": "delta(value_in_eur{instance=\"192.168.1.12:9001\", job=\"gasmeter_exporter\"}[24h]) ",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Gas Consumed Last Week",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(value{instance=\"192.168.1.12:9001\", job=\"gasmeter_exporter\"}[7d])  *0.9587 * 11.404",
     "legendFormat": " "
    },
    {
     "expr": "delta(value_in_eur{instance=\"192.168.1.12:9001\", job=\"gasmeter_exporter\"}[7d])  ",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Gas Consumed Last Month",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(value{instance=\"192.168.1.12:9001\", job=\"gasmeter_exporter\"}[30d])  *0.9587 * 11.404",
     "legendFormat": " "
    },
    {
     "expr": "delta(value_in_eur{instance=\"192.168.1.12:9001\", job=\"gasmeter_exporter\"}[30d]) ",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Gas Consumed Last Year",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(value{instance=\"192.168.1.12:9001\", job=\"gasmeter_exporter\"}[365d])  *0.9587 * 11.404",
     "legendFormat": " "
    },
    {
     "expr": "delta(value_in_eur{instance=\"192.168.1.12:9001\", job=\"gasmeter_exporter\"}[365d])  ",
     "legendFormat": " "
    }
   ]
  }
 ]
}